events {
    worker_connections 1024;
}

stream {
    upstream backend_servers {
        # FQDN - Fully Qualified Domain Name
        server app1:80 weight=5;
        server app2:80 weight=3;
        # Docker private network IP -- without network attachment
        # server 172.17.0.2:80 weight=5;
        # server 172.17.0.3:80 weight=3;
    }

    server {
        listen 80; # The port NGINX listens to for L4 traffic
        proxy_pass backend_servers;
    }
}
