# events {
#     # worker_connections 1024;
# }

# stream {
#     upstream backend_servers {
#         server 192.168.1.10:8080; # Replace with your backend server IP/port
#         server 192.168.1.11:8080;
#     }

#     server {
#         listen 80; # The port NGINX listens to for L4 traffic
#         proxy_pass backend_servers;
#     }
# }
