# /etc/nginx/nginx.conf

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

# =========================================================================
# 1. TCP/UDP CONFIGURATION (Layer 4)
# =========================================================================
stream {
    # Define backend servers for TCP traffic (e.g., Databases, SSH, Redis)
    upstream backend_servers {
        server app1:80 max_fails=3 fail_timeout=30s;
        server app2:80 max_fails=3 fail_timeout=30s;
    }
    # upstream mysql_servers {
    #     server 10.0.2.10:3306 max_fails=3 fail_timeout=30s;
    #     server 10.0.2.11:3306 max_fails=3 fail_timeout=30s;
    # }

    # Handle incoming raw TCP connections
    server {
        listen 3304;
        proxy_pass backend_servers;
        proxy_connect_timeout 5s;
        proxy_timeout 300s;

        # listen 3306;                  # Listen on local TCP port 3306
        # proxy_pass mysql_servers;     # Forward raw traffic to the pool above
        # proxy_connect_timeout 5s;
        # proxy_timeout 300s;
    }
}

# =========================================================================
# 2. HTTP CONFIGURATION (Layer 7)
# =========================================================================
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Basic performance tweaks
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    # Define backend web application servers
    upstream web_app_pool {
        least_conn;                   # Load-balancing algorithm
        # server 127.0.0.1:8081;
        # server 127.0.0.1:8082;
        server app1:80 weight=5;
        server app2:80 weight=3;
        # server 172.17.0.2:80 weight=5;
        # server 172.17.0.3:80 weight=3;
    }

    # Handle incoming HTTP/HTTPS requests
    server {
        listen 80;
        listen [::]:80;
        # server_name example.com www.example.com;      # Domain: /etc/host entry for local PC 
        server_name localhost 127.0.0.1;

        # Web routing block
        location / {
            proxy_pass http://web_app_pool; # Forward traffic as HTTP requests
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/app1/ {
            proxy_pass http://app1:80/;
        }

        location /api/app2/ {
            proxy_pass http://app2:80/;
        }

        # Error tracking
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
    
    ### multi-tenecy achieving with hostname header and wildcard domain system
    server {
        listen 80;
        server_name app1.loadbalancer.com;

        # Web routing block
        location / {
            proxy_pass http://application1; # Forward traffic as HTTP requests
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 80;
        server_name app2.loadbalancer.com;

        # Web routing block
        location / {
            proxy_pass http://application2; # Forward traffic as HTTP requests
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    upstream application1 {
        server app1:80;
    }

    upstream application2 {
        server app2:80;
    }
}
