events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        # FQDN - Fully Qualified Domain Name
        server app1:80 weight=5;
        server app2:80 weight=3;
        # Docker private network IP
        # server 172.17.0.2:80 weight=5;
        # server 172.17.0.3:80 weight=3;
    }

    server {
        listen 80; # The port NGINX listens to for HTTP (Layer 7) traffic

        location / {
            proxy_pass http://backend_servers;
        }
    }
}
