events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        server 172.17.0.02:80 weight=5; # Replace with your backend server IP/port
        server 172.17.0.03:80 weight=3;
    }

    server {
        listen 80; # The port NGINX listens to for L4 traffic
        proxy_pass http://backend_servers;
    }
}
